name: Spring Boot CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: "temurin"
          java-version: "17"

      - name: Show directory structure
        run: |
          echo "Working Directory: $(pwd)"
          ls -R

      - name: Build EurekaServer
        run: |
          cd Experiment4
          mvn -f EurekaServer/pom.xml clean install

      - name: Build ServiceA
        run: |
          cd Experiment4
          mvn -f ServiceA/pom.xml clean install

      - name: Build ServiceB
        run: |
          cd Experiment4
          mvn -f ServiceB/pom.xml clean install

      - name: Test EurekaServer
        run: |
          cd Experiment4
          mvn -f EurekaServer/pom.xml test

      - name: Test ServiceA
        run: |
          cd Experiment4
          mvn -f ServiceA/pom.xml test

      - name: Test ServiceB
        run: |
          cd Experiment4
          mvn -f ServiceB/pom.xml test
